#!/bin/bash

declare A keywords_array

keywords_array["alignas"]="keyword"
keywords_array["alignof"]="keyword"
keywords_array["and"]="keyword"
keywords_array["and_eq"]="keyword"
keywords_array["asm"]="keyword"
keywords_array["atomic_cancel"]="keyword"
keywords_array["atomic_commit"]="keyword"
keywords_array["atomic_noexept"]="keyword"
keywords_array["auto"]="keyword"
keywords_array["bitand"]="keyword"
keywords_array["bitor"]="keyword"
keywords_array["bool"]="keyword"
keywords_array["break"]="keyword"
keywords_array["case"]="keyword"
keywords_array["catch"]="keyword"
keywords_array["char"]="keyword"
keywords_array["char8_t"]="keyword"
keywords_array["char16_t"]="keyword"
keywords_array["char32_t"]="keyword"
keywords_array["class"]="keyword"
keywords_array["compl"]="keyword"
keywords_array["concept"]="keyword"
keywords_array["const"]="keyword"
keywords_array["consteval"]="keyword"
keywords_array["constexpr"]="keyword"
keywords_array["constinit"]="keyword"
keywords_array["const_cast"]="keyword"
keywords_array["continue"]="keyword"
keywords_array["co_await"]="keyword"
keywords_array["co_return"]="keyword"
keywords_array["ci_yield"]="keyword"
keywords_array["decltype"]="keyword"
keywords_array["default"]="keyword"
keywords_array["delete"]="keyword"
keywords_array["do"]="keyword"
keywords_array["double"]="keyword"
keywords_array["dynamic_cast"]="keyword"
keywords_array["else"]="keyword"
keywords_array["enum"]="keyword"
keywords_array["explicit"]="keyword"
keywords_array["export"]="keyword"
keywords_array["extern"]="keyword"
keywords_array["false"]="keyword"
keywords_array["float"]="keyword"
keywords_array["for"]="keyword"
keywords_array["friend"]="keyword"
keywords_array["goto"]="keyword"
keywords_array["if"]="keyword"
keywords_array[" "]="keyword"

echo ${#keywords_array[@]}
echo ${keywords_array["if"]}
