#!/bin/bash

declare A keywords_array

keywords_array["alignas"]="keyword" #C++11
keywords_array["alignof"]="keyword" #C++11
keywords_array["and"]="keyword"
keywords_array["and_eq"]="keyword"
keywords_array["asm"]="keyword"
keywords_array["atomic_cancel"]="keyword" #TM TS
keywords_array["atomic_commit"]="keyword" #TM TS
keywords_array["atomic_noexept"]="keyword" #TM TS
keywords_array["auto"]="keyword"
keywords_array["bitand"]="keyword"
keywords_array["bitor"]="keyword"
keywords_array["bool"]="keyword"
keywords_array["break"]="keyword"
keywords_array["case"]="keyword"
keywords_array["catch"]="keyword"
keywords_array["char"]="keyword"
keywords_array["char8_t"]="keyword" #C++20
keywords_array["char16_t"]="keyword" #C++11
keywords_array["char32_t"]="keyword" #C++11
keywords_array["class"]="keyword"
keywords_array["compl"]="keyword"
keywords_array["concept"]="keyword" #C++20
keywords_array["const"]="keyword"
keywords_array["consteval"]="keyword" #C++20
keywords_array["constexpr"]="keyword" #C++11
keywords_array["constinit"]="keyword" #C++20
keywords_array["const_cast"]="keyword"
keywords_array["continue"]="keyword"
keywords_array["co_await"]="keyword" #C++20
keywords_array["co_return"]="keyword" #C++20
keywords_array["ci_yield"]="keyword" #C++20
keywords_array["decltype"]="keyword" #C++11
keywords_array["default"]="keyword"
keywords_array["delete"]="keyword"
keywords_array["do"]="keyword"
keywords_array["double"]="keyword"
keywords_array["dynamic_cast"]="keyword"
keywords_array["else"]="keyword"
keywords_array["enum"]="keyword"
keywords_array["explicit"]="keyword"
keywords_array["export"]="keyword"
keywords_array["extern"]="keyword"
keywords_array["false"]="keyword"
keywords_array["float"]="keyword"
keywords_array["for"]="keyword"
keywords_array["friend"]="keyword"
keywords_array["goto"]="keyword"
keywords_array["if"]="keyword"
keywords_array["inline"]="keyword"
keywords_array["int "]="keyword"
keywords_array["long"]="keyword"
keywords_array["mutable"]="keyword"
keywords_array["namespace"]="keyword"
keywords_array["new"]="keyword"
keywords_array["noexcept"]="keyword" #C++11
keywords_array["not"]="keyword"
keywords_array["not_eq"]="keyword"
keywords_array["nullptr"]="keyword" #C++11
keywords_array["operator"]="keyword"
keywords_array["or"]="keyword"
keywords_array["or_eq"]="keyword"
keywords_array["private"]="keyword"
keywords_array["protected"]="keyword"
keywords_array["public"]="keyword"
keywords_array["reflexpr"]="keyword" #reflection TS
keywords_array["register"]="keyword"
keywords_array["reinterpret_cast"]="keyword"
keywords_array["requires"]="keyword" #C++20
keywords_array["return"]="keyword"
keywords_array["short"]="keyword"
keywords_array["signed"]="keyword"
keywords_array["sizeof"]="keyword"
keywords_array["static"]="keyword"
keywords_array["static_assert"]="keyword" #C++11
keywords_array["static_cast"]="keyword"
keywords_array["struct"]="keyword"
keywords_array["switch"]="keyword"
keywords_array["synchronized"]="keyword" #TM TS

keywords_array["template"]="keyword"
keywords_array["this"]="keyword"
keywords_array["thread_local"]="keyword" #C++11
keywords_array["throw"]="keyword"
keywords_array["true"]="keyword"
keywords_array["try"]="keyword"
keywords_array["typedef"]="keyword"
keywords_array["typeid"]="keyword"
keywords_array["typename"]="keyword"
keywords_array["union"]="keyword"
keywords_array["unsigned"]="keyword"
keywords_array["using"]="keyword"
keywords_array["virtual"]="keyword"
keywords_array["void"]="keyword"
keywords_array["volatile"]="keyword"
keywords_array["wchar_t"]="keyword"
keywords_array["while"]="keyword"
keywords_array["xor"]="keyword"
keywords_array["xor_eq"]="keyword"
keywords_array["final"]="keyword" #C++11
keywords_array["override"]="keyword" #C++11
keywords_array["transaction_safe"]="keyword" #TM TS
keywords_array["transaction_safe_dynamic"]="keyword" #TM TS

keywords_array["-if"]="preprocessor"
keywords_array["-elif"]="preprocessor"
keywords_array["-else"]="preprocessor"
keywords_array["-endif"]="preprocessor"
keywords_array["-ifdef"]="preprocessor"
keywords_array["-ifndef"]="preprocessor"
keywords_array["-elifdef"]="preprocessor" #C++23
keywords_array["-elifndef"]="preprocessor" #C++23
keywords_array["-define "]="preprocessor"
keywords_array["-undef "]="preprocessor"
keywords_array["-include "]="preprocessor"
keywords_array["-line "]="preprocessor"
keywords_array["-error "]="preprocessor"
keywords_array["-warning "]="preprocessor" #C++23
keywords_array["-pragma "]="preprocessor"
keywords_array["-defined"]="preprocessor"
keywords_array["-__has_include"]="preprocessor" #C++17
keywords_array["-__has_cpp_attribute"]="preprocessor" #C++20
keywords_array["-export"]="preprocessor" #C++20
keywords_array["-import"]="preprocessor" #C++20
keywords_array["-module"]="preprocessor" #C++20

keywords_array["tbyte"]="specific"
keywords_array["ubyte"]="specific"
keywords_array["int8t"]="specific"
keywords_array["uint8t"]="specific"
keywords_array["int16t"]="specific"
keywords_array["uint16t"]="specific"
keywords_array["int32t"]="specific"
keywords_array["uint32t"]="specific"
keywords_array["int64t"]="specific"
keywords_array["uint64t"]="specific"


echo ${#keywords_array[@]}
echo ${keywords_array["if"]}
